/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt",{title:"Instru��es de acessibilidade",contents:"Conte�do de ajuda. Use a tecla ESC para fechar esta janela.",legend:[{name:"Geral",items:[{name:"Barra de ferramentas do editor",legend:"Clique em ${toolbarFocus} para navegar na barra de ferramentas. Para navegar entre o grupo da barra de ferramentas anterior e seguinte use TAB e SHIFT+TAB. Para navegar entre o bot�o da barra de ferramentas seguinte e anterior use a SETA DIREITA ou SETA ESQUERDA. Carregue em ESPA�O ou ENTER para ativar o bot�o da barra de ferramentas."},
{name:"Janela do editor",legend:"Dentro de uma janela de di�logo, use TAB para navegar para o campo seguinte; use SHIFT + TAB para mover para o campo anterior, use ENTER para submeter a janela, use ESC para cancelar a janela. Para as janelas que tenham v�rios separadores, use ALT + F10 para navegar na lista de separadores. Na lista pode mover entre o separador seguinte ou anterior com SETA DIREITA e SETA ESQUERDA, respetivamente"},{name:"Menu de contexto do editor",legend:"Clique em ${contextMenu} ou TECLA APLICA��O para abrir o menu de contexto. Depois v� para a op��o do menu seguinte com TAB ou SETA PARA BAIXO. V� para a op��o anterior com  SHIFT+TAB ou SETA PARA CIMA. Pressione ESPA�O ou ENTER para selecionar a op��o do menu.  Abra o submenu da op��o atual com ESPA�O, ENTER ou SETA DIREITA. V� para o item do menu contentor com ESC ou SETA ESQUERDA. Feche o menu de contexto com ESC."},
{name:"Editor de caixa em lista",legend:"Dentro de uma lista, para navegar para o item seguinte da lista use TAB ou SETA PARA BAIXO. Para o item anterior da lista use SHIFT+TAB ou SETA PARA BAIXO. Carregue em ESPA�O ou ENTER para selecionar a op��o lista. Carregue em ESC para fechar a caixa da lista."},{name:"Editor da barra de caminho dos elementos",legend:"Clique em ${elementsPathFocus} para navegar na barra de caminho dos elementos. Para o bot�o do elemento seguinte use TAB ou SETA DIREITA. para o bot�o anterior use SHIFT+TAB ou SETA ESQUERDA. Carregue em ESPA�O ou ENTER para selecionar o elemento no editor."}]},
{name:"Comandos",items:[{name:"Comando de anular",legend:"Carregar ${undo}"},{name:"Comando de refazer",legend:"Clique ${redo}"},{name:"Comando de negrito",legend:"Pressione ${bold}"},{name:"Comando de it�lico",legend:"Pressione ${italic}"},{name:"Comando de sublinhado",legend:"Pressione ${underline}"},{name:"Comando de hiperliga��o",legend:"Pressione ${link}"},{name:"Comando de ocultar barra de ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Aceder ao comando espa�o de foco anterior",
legend:"Clique em ${accessPreviousSpace} para aceder ao espa�o do focos inalcan��vel mais perto antes do sinal de omiss�o, por exemplo: dois elementos HR adjacentes. Repetir a combina��o da chave para alcan�ar os espa�os dos focos distantes."},{name:"Acesso comando do espa�o focus seguinte",legend:"Pressione ${accessNextSpace} para aceder ao espa�o do focos inalcan��vel mais perto depois do sinal de omiss�o, por exemplo: dois elementos HR adjacentes. Repetir a combina��o da chave para alcan�ar os espa�os dos focos distantes."},
{name:"Ajuda a acessibilidade",legend:"Pressione ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Separador",pause:"Pausa",capslock:"Mai�sculas",escape:"Esc",pageUp:"Subir p�gina",pageDown:"Descer p�gina",leftArrow:"Seta esquerda",upArrow:"Seta para cima",rightArrow:"Seta direita",downArrow:"Seta para baixo",insert:"Inserir",leftWindowKey:"Tecla esquerda Windows",rightWindowKey:"Tecla direita Windows",selectKey:"Selecionar tecla",
numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiplicar",add:"Adicionar",subtract:"Subtrair",decimalPoint:"Ponto decimal",divide:"Separar",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Ponto e v�rgula",equalSign:"Sinald e igual",comma:"V�rgula",
dash:"Cardinal",period:"Ponto",forwardSlash:"Forward Slash",graveAccent:"Acento grave",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Plica"});