/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","ro",{title:"Instruc?iuni Accesibilitate",contents:"Cuprins. Pentru a �nchide acest dialog, apasa?i tasta ESC.",legend:[{name:"General",items:[{name:"Editor bara de instrumente.",legend:"Apasa ${toolbarFocus} pentru a naviga pe de instrumente. Pentru deplasarea la urmatorul sau anteriorul grup de instrumente se folosesc tastele TAB ?i SHIFT+TAB. Pentru deplasare pe urmatorul sau anteriorul instrument se folosesc tastele SAGEATA DREAPTA sau SAGEATA ST�NGA. Tasta SPA?IU sau ENTER activeaza instrumentul."},
{name:"Dialog editor",legend:"�n interiorul unui dialog, se apasa TAB pentru navigarea la urmatorul element de dialog, SHIFT+TAB pentru deplasarea la anteriorul element de dialog, ENTER pentru validare dialog, ESC pentru anulare dialog. C�nd un dialog are sec?iuni multiple, lista sec?iunilor este accesibila cu ALT+F10 sau cu TAB ca parte a ordonarii sec?ionarii dialogului. Cu lista sec?iunii activata, deplasarea �nainte �napoi se face cu tastele SAGEATA DREAPTA ?i respectiv ST�NGA."},{name:"Editor meniu contextual",
legend:"Apasa ${contextMenu} sau TASTA MENIU pentru a deschide meniul contextual. Se trece la urmatoarea op?iune din meniu cu TAB sau SAGEATA JOS. La op?iunea anterioara cu SHIFT+TAB sau SAGEATA SUS. Se apasa SPA?IU sau ENTER pentru a selecta op?iunea. Deschide sub-meniul op?iunii curente cu SPA?IU sau ENTER sau SAGEATA DREAPTA. Se revine la elementul din meniul parinte cu ESC sau SAGEATA ST�NGA. �nchide meniul de context cu ESC."},{name:"Caseta lista a editorului",legend:"�n interiorul unei liste, treci la urmatorull element cu TAB sau SAGEATA JOS. Treci la elementul anterior din lista cu SHIFT+TAB sau SAGEATA SUS. Apasa SPA?IU sau ENTER pentru a selecta op?iunea din lista. Apasa ESC pentru a �nchide lista."},
{name:"Bara caii editorului de elemente",legend:"Apasa ${elementsPathFocus} pentru navigare pe elementele barei. Mergi la urmatorul buton cu TAB sau SAGEATA JOS. Treci la butonul anterior din lista cu SHIFT+TAB sau SAGEATA SUS. Apasa SPA?IU sau ENTER pentru a selecta butonul �n editor."}]},{name:"Comenzi",items:[{name:"Revino anterior (Undo)",legend:"Apasa ${undo}"},{name:"Comanda precedenta",legend:"Apasa ${redo}"},{name:"�ngro?at (Bold)",legend:"Apasa ${bold}"},{name:"�nclinat (Italic)",legend:"Apasa ${italic}"},
{name:"Subliniere (Underline)",legend:"Apasa ${underline}"},{name:"Legatura (Link)",legend:"Apasa ${link}"},{name:"Desfa?urare Bara instrumente",legend:"Apasa ${toolbarCollapse}"},{name:"Accesare spa?iu focus anterior",legend:"Apasa ${accessPreviousSpace} pentru a accesa cel mai apropiat spa?iu focus indisponibil �naintea cursorului, de exemplu: 2 elemente adiacente HR. Repeta combina?ia de taste pentru a accesa spa?iile �ndepartate de focus."},{name:"Accesare spa?iu focus urmator",legend:"Apasa ${accessNextSpace} pentru a accesa cel mai apropiat spa?iu focus indisponibil dupa cursor, de exemplu: 2 elemente adiacente HR. Repeta combina?ia de taste pentru a accesa spa?iile �ndepartate de focus."},
{name:"Ajutor Accesibilitate",legend:"Apasa ${a11yHelp}"},{name:"Adauga ca Text simplu (Plain Text)",legend:"Apasa ${pastetext}",legendEdge:"Apasa ${pastetext}, urmat de ${paste}"}]}],tab:"TAB",pause:"Pauza",capslock:"Majuscule",escape:"Esc - renun?a",pageUp:"Pagina sus",pageDown:"Sageata jos",leftArrow:"Sageata st�nga",upArrow:"Sageata sus",rightArrow:"Sageata dreapta",downArrow:"Sageata jos",insert:"Insereaza",leftWindowKey:"Windows st�nga",rightWindowKey:"Windows dreapta",selectKey:"Tasta Selec?ie",
numpad0:"0 Numeric",numpad1:"1 Numeric",numpad2:"2 Numeric",numpad3:"3 Numeric",numpad4:"4 Numeric",numpad5:"5 Numeric",numpad6:"6 Numeric",numpad7:"7 Numeric",numpad8:"8 Numeric",numpad9:"9 Numeric",multiply:"�nmul?ire",add:"Adunare",subtract:"Scadere",decimalPoint:"Punct zecimal",divide:"�mpar?ire",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"NumLock",scrollLock:"Scroll Lock",semiColon:"Punct ?i virgula",equalSign:"Egal",comma:"Virgula",
dash:"Linie",period:"Punct",forwardSlash:"Slash",graveAccent:"Accent grav",openBracket:"Paranteza dreapta st�nga",backSlash:"Backslash",closeBracket:"Paranteza dreapta dreapta",singleQuote:"Ghilimea simpla"});